version: '3'

services:
  blue:
    image: nginx:latest
    container_name: blue
    volumes:
      - ./blue:/usr/share/nginx/html
    ports:
      - "8081:80"

  green:
    image: nginx:latest
    container_name: green
    volumes:
      - ./green:/usr/share/nginx/html
    ports:
      - "8082:80"
